name: mywall
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+10

environment:
  sdk: '>=3.7.2 <5.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  share_plus: ^11.1.0
  path_provider: ^2.0.15
  flutter_dotenv: ^6.0.0
  wallpaper_manager_flutter: 1.0.1
  # socket_io_client: ^2.0.3
  web_socket_channel: ^3.0.3
  permission_handler: ^11.0.1
  # google_mobile_ads: ^2.1.0
  provider: ^6.0.5  
  google_mobile_ads: ^6.0.0
  shared_preferences: ^2.2.2
  image: ^4.0.15
  in_app_review: ^2.0.6  
  url_launcher: ^6.1.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # badges: ^3.1.2
  flutter_app_badger: ^1.5.0
  app_badger: ^0.0.1
  flutter_local_notifications: ^17.1.2

  # google_mobile_ads: ^1.2.0

  # google_mobile_ads: ^2.4.0
  # gallery_saver: ^3.0.3
  # image_gallery_saver: ^2.0.3

  # wallpaper_manager_flutter:  1.0.1
  # flutter_wallpaper_manager: ^0.0.4  # Add this line
  # wallpaper_manager: ^1.1.3
  # wallpaper_manager_flutter: ^0.0.6  
  # wallpaper: ^2.0.0
  # wallpaper_manager: ^1.1.3
  # wallpaper_manager_flutter: ^0.0.3
  # wallpaper_manager_flutter: ^0.0.3
  # wallpaper_manager_flutter: ^0.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.5.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - .env
    - assets/category/Jhope.jpg
    - assets/category/Jimin.jpg
    - assets/category/Jin.jpg
    - assets/category/Jungkok.jpg
    - assets/category/RM.jpg
    - assets/category/Suga.jpg
    - assets/category/Vee.jpg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
